branches:
  except:
    - dev
language: cpp
matrix:
  include:
    - name: "linux-x64"
      os: linux
      dist: bionic
      env: EXTRA_FLAGS='target_cpu="x64"'
    - name: "linux-x86"
      os: linux
      dist: bionic
      env: EXTRA_FLAGS='target_cpu="x86"'
    - name: "linux-arm64"
      os: linux
      dist: bionic
      env: EXTRA_FLAGS='target_cpu="arm64"'
    - name: "linux-arm"
      os: linux
      dist: bionic
      env: EXTRA_FLAGS='target_cpu="arm"'
    - name: "openwrt-mipsel_24kc"
      os: linux
      dist: bionic
      env: EXTRA_FLAGS='
             target_cpu="mipsel"
             mips_arch_variant="r2" mips_float_abi="soft" mips_tune="24kc"
             use_allocator="none" use_allocator_shim=false
             use_lld=false use_gold=false
             ldso_path="/lib/ld-musl-mipsel-sf.so.1"
             custom_toolchain="//build/toolchain/linux:clang_mipsel_openwrt"'
           OPENWRT_FLAGS='arch=mipsel_24kc release=19.07.2 gcc_ver=7.5.0 target=ramips subtarget=rt305x'
    - name: "openwrt-x86_64"
      os: linux
      dist: bionic
      env: EXTRA_FLAGS='
             target_cpu="x64"
             use_allocator="none" use_allocator_shim=false
             custom_toolchain="//build/toolchain/linux:clang_x64_openwrt"'
           OPENWRT_FLAGS='arch=x86_64 release=19.07.2 gcc_ver=7.5.0 target=x86 subtarget=64'
    - name: "openwrt-arm64"
      os: linux
      dist: bionic
      env: EXTRA_FLAGS='
             target_cpu="arm64"
             use_allocator="none" use_allocator_shim=false
             custom_toolchain="//build/toolchain/linux:clang_arm64_openwrt"'
           OPENWRT_FLAGS='arch=aarch64 release=19.07.2 gcc_ver=7.5.0 target=armvirt subtarget=64'
    - name: "osx"
      os: osx
      osx_image: xcode11.3
addons:
  apt:
    packages:
      - ninja-build
      - pkg-config
      - libnss3-dev
      - qemu-user
  homebrew:
    packages:
      - ninja
      - ccache
    update: true
cache:
  directories:
    - $HOME/.ccache
    - src/out/sysroot-build/openwrt
script:
  - ./tools/import-upstream.sh
  - ( cd src; ./get-clang.sh )
  - ccache -s
  - ( cd src; ./build.sh )
  - ccache -s
  - ./tests/basic.sh src/out/Release/naive
  - export BUILD_NAME="naiveproxy-$TRAVIS_BRANCH-$TRAVIS_JOB_NAME"
  - mkdir $BUILD_NAME
  - cp src/out/Release/naive src/config.json LICENSE USAGE.txt $BUILD_NAME
  - tar cJf $BUILD_NAME.tar.xz $BUILD_NAME
deploy:
  provider: releases
  api_key:
    secure: hZ+M3GvNpPPMri0u7HkeDM8qCNSzCP2kBxL/68XgF3uvMDkJRX5/gyq27EoQMHyRxni759LlwHttRn6nHSg/CwNgK4fD4WPZWU99XIWKdlI+P1AQkHThjNtABv3P7JOq1HxyuwrcaBPybnDjsQTFE6HG5zsIhXZlUTCHbndCBpYPuDnaqKJJUv4/WzoEjXAlBSkAsBGhEQv+HZhaupw5vSkDkulNgXZrXOoO6uzAtAiR5St38dV7cWXgk6UwoyrVaV8cO0cltveyEPkGYMXJh6YkopJjSVrkYlI8vWsA8CgwdhXwAkYoG1uaIDUdNdlrBXNuA0BOFcU3iEo3D9H/z1/WQUnCuAOVCkYC/QhkTCsioQ5vaNA56+3uY8KOSDNo8XxxBzRIUSwul2lwHCNl6+cf1EhO9brI3Q8q/ZPZLmNIqYDXAI29/MMC13g/ql8UUcy2TwGrx2OE73SIzVBm2hVYI6FFs2hjJzMkknV83K0kr515gXrI+p7ANqnA9vdRBx7zMdOT1etFeuD06wjbLGLmHTS4ykhDYl6wn26fJHm3/OkqNyWllghc8DZnpAHh5AAYrrTIQPlSgtyqGL2qCoCPHbb2WgWewSVhqY+p7JMPchAc6myW3H2c7yL+TDMdRcr9I7DDOpvvfMoGx527Lji54mxGdZmdEpSGxi9Rx3g=
  file: $BUILD_NAME.tar.xz
  skip_cleanup: true
  name: $TRAVIS_BRANCH
  prerelease: true
  on:
    tags: true
    all_branches: true
